import calculator
from PySide6.QtCore import Qt
from PySide6.QtWidgets import QWidget, QPushButton, QMainWindow, QGridLayout, QLabel, QVBoxLayout, QHBoxLayout, QLineEdit

phrase = ""


class MainWindow(QMainWindow):

    def __init__(self):
        super().__init__()

        self.setWindowTitle("Classic Calculator")
        self.setFixedSize(400, 500)

        mainContainer = QWidget()
        mainLayout = QVBoxLayout(mainContainer)

        buttonsGrid = QGridLayout()

        # FUNCTIONAL AND SIGNATURES BUTTONS
        plusButton = QPushButton()
        plusButton.setText("+")
        plusButton.setMinimumHeight(40)
        minusButton = QPushButton()
        minusButton.setText("-")
        minusButton.setMinimumHeight(40)
        multiplyButton = QPushButton()
        multiplyButton.setText("×")
        multiplyButton.setMinimumHeight(40)
        divideButton = QPushButton()
        divideButton.setText("÷")
        divideButton.setMinimumHeight(40)
        moduloButton = QPushButton()
        moduloButton.setText("%")
        moduloButton.setMinimumHeight(40)
        sqrtButton = QPushButton()
        sqrtButton.setText("√")
        sqrtButton.setMinimumHeight(40)
        squareButton = QPushButton()
        squareButton.setText("x²")
        squareButton.setMinimumHeight(40)
        powerButton = QPushButton()
        powerButton.setText("xʸ")
        powerButton.setMinimumHeight(40)
        plusMinusButton = QPushButton()
        plusMinusButton.setText("±")
        plusMinusButton.setMinimumHeight(40)
        absoluteValueButton = QPushButton()
        absoluteValueButton.setText("|x|")
        absoluteValueButton.setMinimumHeight(40)
        equalsButton = QPushButton()
        equalsButton.setText("=")
        equalsButton.setMinimumHeight(40)
        periodButton = QPushButton()
        periodButton.setText(".")
        periodButton.setMinimumHeight(40)
        decimalLeftButton = QPushButton()
        decimalLeftButton.setText("←.")
        decimalLeftButton.setMinimumHeight(40)
        decimalRightButton = QPushButton()
        decimalRightButton.setText(".→")
        decimalRightButton.setMinimumHeight(40)
        cancelButton = QPushButton()
        cancelButton.setText("C")
        cancelButton.setMinimumHeight(40)
        backspaceButton = QPushButton()
        backspaceButton.setText("⌫")
        backspaceButton.setMinimumHeight(40)
        sinButton = QPushButton()
        sinButton.setText("sin")
        sinButton.setMinimumHeight(40)
        cosButton = QPushButton()
        cosButton.setText("cos")
        cosButton.setMinimumHeight(40)
        tanButton = QPushButton()
        tanButton.setText("tan")
        tanButton.setMinimumHeight(40)
        logButton = QPushButton()
        logButton.setText("log")
        logButton.setMinimumHeight(40)
        customLogButton = QPushButton()
        customLogButton.setText("logₓy")
        customLogButton.setMinimumHeight(40)
        lnButton = QPushButton()
        lnButton.setText("ln")
        lnButton.setMinimumHeight(40)
        factorialButton = QPushButton()
        factorialButton.setText("n!")
        factorialButton.setMinimumHeight(40)
        modButton = QPushButton()
        modButton.setText("mod")
        modButton.setMinimumHeight(40)
        piButton = QPushButton()
        piButton.setText("π")
        piButton.setMinimumHeight(40)
        eButton = QPushButton()
        eButton.setText("e")
        eButton.setMinimumHeight(40)
        openParenButton = QPushButton()
        openParenButton.setText("(")
        openParenButton.setMinimumHeight(40)
        closeParenButton = QPushButton()
        closeParenButton.setText(")")
        closeParenButton.setMinimumHeight(40)
        reciprocalButton = QPushButton()
        reciprocalButton.setText("1/x")
        reciprocalButton.setMinimumHeight(40)
        expButton = QPushButton()
        expButton.setText("EXP")
        expButton.setMinimumHeight(40)
        asinButton = QPushButton()
        asinButton.setText("sin⁻¹")
        asinButton.setMinimumHeight(40)
        acosButton = QPushButton()
        acosButton.setText("cos⁻¹")
        acosButton.setMinimumHeight(40)
        atanButton = QPushButton()
        atanButton.setText("tan⁻¹")
        atanButton.setMinimumHeight(40)
        xRootButton = QPushButton()
        xRootButton.setText("ˣ√")
        xRootButton.setMinimumHeight(40)

        # DIGIT BUTTONS
        oneButton = QPushButton()
        oneButton.setText("1")
        oneButton.setMinimumHeight(40)
        twoButton = QPushButton()
        twoButton.setText("2")
        twoButton.setMinimumHeight(40)
        threeButton = QPushButton()
        threeButton.setText("3")
        threeButton.setMinimumHeight(40)
        fourButton = QPushButton()
        fourButton.setText("4")
        fourButton.setMinimumHeight(40)
        fiveButton = QPushButton()
        fiveButton.setText("5")
        fiveButton.setMinimumHeight(40)
        sixButton = QPushButton()
        sixButton.setText("6")
        sixButton.setMinimumHeight(40)
        sevenButton = QPushButton()
        sevenButton.setText("7")
        sevenButton.setMinimumHeight(40)
        eightButton = QPushButton()
        eightButton.setText("8")
        eightButton.setMinimumHeight(40)
        nineButton = QPushButton()
        nineButton.setText("9")
        nineButton.setMinimumHeight(40)
        zeroButton = QPushButton()
        zeroButton.setText("0")
        zeroButton.setMinimumHeight(40)

        # CONNECTING FUNCTIONS TO FUNCTIONAL BUTTONS
        plusButton.clicked.connect(lambda: self.construct("+"))
        minusButton.clicked.connect(lambda: self.construct("-"))
        multiplyButton.clicked.connect(lambda: self.construct("×"))
        divideButton.clicked.connect(lambda: self.construct("÷"))
        moduloButton.clicked.connect(lambda: self.construct("%"))
        sqrtButton.clicked.connect(lambda: self.construct("√"))
        squareButton.clicked.connect(lambda: self.construct("^2"))
        powerButton.clicked.connect(lambda: self.construct("^"))
        plusMinusButton.clicked.connect(lambda: self.construct("±"))
        absoluteValueButton.clicked.connect(lambda: self.construct("|x|"))
        equalsButton.clicked.connect(lambda: self.construct("="))
        periodButton.clicked.connect(lambda: self.construct("."))
        decimalLeftButton.clicked.connect(lambda: self.construct("←."))
        decimalRightButton.clicked.connect(lambda: self.construct(".→"))
        cancelButton.clicked.connect(lambda: self.clearScreen())
        backspaceButton.clicked.connect(lambda: self.cancelChar())
        sinButton.clicked.connect(lambda: self.construct("sin"))
        cosButton.clicked.connect(lambda: self.construct("cos"))
        tanButton.clicked.connect(lambda: self.construct("tan"))
        logButton.clicked.connect(lambda: self.construct("log"))
        customLogButton.clicked.connect(lambda: self.construct("logₓy"))
        lnButton.clicked.connect(lambda: self.construct("ln"))
        factorialButton.clicked.connect(lambda: self.construct("n!"))
        modButton.clicked.connect(lambda: self.construct("mod"))
        piButton.clicked.connect(lambda: self.construct("π"))
        eButton.clicked.connect(lambda: self.construct("e"))
        openParenButton.clicked.connect(lambda: self.construct("("))
        closeParenButton.clicked.connect(lambda: self.construct(")"))
        reciprocalButton.clicked.connect(lambda: self.construct("1/x"))
        expButton.clicked.connect(lambda: self.construct("EXP"))
        asinButton.clicked.connect(lambda: self.construct("sin⁻¹"))
        acosButton.clicked.connect(lambda: self.construct("cos⁻¹"))
        atanButton.clicked.connect(lambda: self.construct("tan⁻¹"))
        xRootButton.clicked.connect(lambda: self.construct("ˣ√"))

        # CONNECTING FUNCTIONS TO DIGIT NUMBERS
        oneButton.clicked.connect(lambda: self.construct("1"))
        twoButton.clicked.connect(lambda: self.construct("2"))
        threeButton.clicked.connect(lambda: self.construct("3"))
        fourButton.clicked.connect(lambda: self.construct("4"))
        fiveButton.clicked.connect(lambda: self.construct("5"))
        sixButton.clicked.connect(lambda: self.construct("6"))
        sevenButton.clicked.connect(lambda: self.construct("7"))
        eightButton.clicked.connect(lambda: self.construct("8"))
        nineButton.clicked.connect(lambda: self.construct("9"))
        zeroButton.clicked.connect(lambda: self.construct("0"))

        # ADDING BUTTONS TO GRID
        buttonsGrid.addWidget(piButton, 0, 0)
        buttonsGrid.addWidget(eButton, 0, 1)
        buttonsGrid.addWidget(openParenButton, 0, 2)
        buttonsGrid.addWidget(closeParenButton, 0, 3)
        buttonsGrid.addWidget(expButton, 0, 4)
        buttonsGrid.addWidget(cancelButton, 0, 5)
        buttonsGrid.addWidget(backspaceButton, 0, 6)
        buttonsGrid.addWidget(sinButton, 1, 0)
        buttonsGrid.addWidget(cosButton, 1, 1)
        buttonsGrid.addWidget(tanButton, 1, 2)
        buttonsGrid.addWidget(asinButton, 1, 3)
        buttonsGrid.addWidget(acosButton, 1, 4)
        buttonsGrid.addWidget(atanButton, 1, 5)
        buttonsGrid.addWidget(moduloButton, 1, 6)
        buttonsGrid.addWidget(modButton, 2, 0)
        buttonsGrid.addWidget(customLogButton, 2, 1)
        buttonsGrid.addWidget(lnButton, 2, 2)
        buttonsGrid.addWidget(sevenButton, 2, 3)
        buttonsGrid.addWidget(eightButton, 2, 4)
        buttonsGrid.addWidget(nineButton, 2, 5)
        buttonsGrid.addWidget(divideButton, 2, 6)
        buttonsGrid.addWidget(sqrtButton, 3, 0)
        buttonsGrid.addWidget(xRootButton, 3, 1)
        buttonsGrid.addWidget(factorialButton, 3, 2)
        buttonsGrid.addWidget(fourButton, 3, 3)
        buttonsGrid.addWidget(fiveButton, 3, 4)
        buttonsGrid.addWidget(sixButton, 3, 5)
        buttonsGrid.addWidget(multiplyButton, 3, 6)
        buttonsGrid.addWidget(squareButton, 4, 0)
        buttonsGrid.addWidget(powerButton, 4, 1)
        buttonsGrid.addWidget(absoluteValueButton, 4, 2)
        buttonsGrid.addWidget(oneButton, 4, 3)
        buttonsGrid.addWidget(twoButton, 4, 4)
        buttonsGrid.addWidget(threeButton, 4, 5)
        buttonsGrid.addWidget(plusButton, 4, 6)
        buttonsGrid.addWidget(reciprocalButton, 5, 0)
        buttonsGrid.addWidget(decimalLeftButton, 5, 1)
        buttonsGrid.addWidget(decimalRightButton, 5, 2)
        buttonsGrid.addWidget(plusMinusButton, 5, 3)
        buttonsGrid.addWidget(zeroButton, 5, 4)
        buttonsGrid.addWidget(periodButton, 5, 5)
        buttonsGrid.addWidget(minusButton, 5, 6)
        buttonsGrid.addWidget(equalsButton, 6, 0, 1, 7)

        # NUMBERS AND RESULT SCREEN
        self.screen = QLineEdit()
        self.screen.setReadOnly(True)
        self.screen.setFixedHeight(100)
        self.screen.setAlignment(Qt.AlignmentFlag.AlignRight)
        self.screen.setObjectName("screen")
        # MAIN LAYOUT IS BUILT
        mainLayout.addWidget(self.screen)
        mainLayout.addLayout(buttonsGrid)

        # MAIN LAYOUT IS SET
        self.setCentralWidget(mainContainer)

    def construct(self, parameter):
        if (parameter == "="):
            self.send()
            return
        if (parameter == "1/x"):
            self.screen.setText("1/(" + self.screen.text() + ")")
            return
        self.screen.setText(self.screen.text() + parameter)

    def send(self):
        expression: str = str(self.screen.text())
        res = calculator.calculate(expression)
        self.screen.setText(str(res))

    def cancelChar(self):
        expression: str = str(self.screen.text())
        self.screen.setText(expression[:-1])

    def clearScreen(self):
        self.screen.setText("")
